Algoritmo "calcularmedia"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/7/2020
Var
// Seção de Declarações das variáveis 
nt1, nt2, md:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informar uma nota. ")
leia(nt1)
escreva("A próxima nota. ")
leia(nt2)

md <- (nt1 + nt2) /2

escreva("A média entre as notas é: ", md)

Fimalgoritmo