Algoritmo "calculandoseno"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/7/2020
Var
// Seção de Declarações das variáveis 
angulo, s: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Informe um angulo: ")
leia(angulo)

s <- sen(grauprad(angulo))

escreva("O seno de", angulo, " é igual a ", s)


Fimalgoritmo