Algoritmo "cacularoraio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/7/2020
Var
// Seção de Declarações das variáveis 
r, resul, phi: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Infor o valor do raio: ")
leia(r)

// declarar valor de phi.
phi <- 3.14159

resul <- phi*(r ^ 2)

escreva("O valor do raio será: ", resul)


Fimalgoritmo