Algoritmo "combinacoes"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/8/2020
Var
   // Seção de Declarações das variáveis
   c1, c2: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para c1 <- 1 ate 3 faca
      para c2 <- 1 ate 3 faca
         escreval(c1,",",c2)
      Fimpara
   Fimpara

Fimalgoritmo