Algoritmo "paraquadradodeumnumero"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/8/2020
Var
// Seção de Declarações das variáveis 
   c, n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c <- 15 ate 200 passo 1 faca
        n <- c * c
        
        escreva(n)
   Fimpara

Fimalgoritmo