Algoritmo "paratabuada"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/8/2020
Var
// Seção de Declarações das variáveis 
   c, n, v: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n <- 7
   Para c<- 1 ate 10 passo 1 faca
        v <- c * n
        
        escreval(n," x ",c," = ",v)
   Fimpara

Fimalgoritmo