Algoritmo "parouimpar"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/7/2020
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um númeor")
leia(num)

//aplicar estrutra de dicisao.

num <- num % 2

Se num = 0 Entao
   escreva("Numero par.")
   
   Senao
   escreva("Numero impar.")
Fimse

Fimalgoritmo