Algoritmo "quadradodointeiro"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/8/2020
Var
// Seção de Declarações das variáveis
   cont, n, vl: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    cont <- 15

   Repita
      vl <- cont
      n <- vl * cont
      escreva(n)
      cont<- cont + 1
   Ate (cont > 200)

Fimalgoritmo