Algoritmo "somarinteiro"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/8/2020
Var
   // Seção de Declarações das variáveis
   cont, n: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Enquanto (cont <= 100 ) Faca
      n <- n + cont
      cont <- cont + 1
   Fimenquanto

   escreva("A soma dos inteiros de 0 a 100 e: ",n)

Fimalgoritmo