Algoritmo "somareexbiroresultado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/7/2020
Var
// Seção de Declarações das variáveis 
n1, n2, sm: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite um número.")
leia(n1)
escreval("Digite outro número")
leia(n2)

sm <- n1 + n2

escreva("A soma entre os números digitados é: ",)

Fimalgoritmo