Algoritmo "vetor1a10"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/8/2020
Var
// Seção de Declarações das variáveis 
   a: vetor [1..10] de inteiro
   i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para i <- 1 ate 10 passo 1 faca
        a[i] <- i
   Fimpara
   
   Para i <- 1 ate 10 passo 1 faca
      escreva(a[i])
   Fimpara

Fimalgoritmo